Repository DeveloperAcademy-POSTECH/MC3-Team13-Inception, pull requests merged in 2022-08, with the labels that each got.

#46 ✨ feat : 수면 기록 화면 delete 기능 구현
  Inception/Inception/Global/CoreData/SleepTrackDataManager.swift
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.storyboard
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
Labels: 😎 밀리, 📄 SleepTrackerView, 🗂 SaveData

#48 ✨ feat : alarmList View CRUD 구현 및 coreDataManager 개선
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/CoreData/AlarmDataManager.swift
  Inception/Inception/Global/CoreData/Inception.xcdatamodeld/Inception.xcdatamodel/contents
  Inception/Inception/Global/CoreData/SleepTrackDataManager.swift
  Inception/Inception/Network/Models/Alarm.swift
  Inception/Inception/Network/Models/SleepRecord.swift
  Inception/Inception/Network/Models/SleepRecordItem+CoreDataProperties.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmList/AlarmListViewController.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
  Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
  Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.storyboard
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
  Inception/Inception/ViewController.swift
Labels: 📄 AlarmListView, 📄 SleepTrackerView, 🗂 SaveData

#50 🚚 move : 파일 및 폴더 이동
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Base.lproj/Main.storyboard
  Inception/Inception/Global/Resource/Sounds/alarmSound.m4a
  Inception/Inception/Global/Supports/AppDelegate.swift
  Inception/Inception/Global/Supports/Info.plist
  Inception/Inception/Global/Supports/SceneDelegate.swift
  Inception/Inception/Network/Manager/AlarmDataManager.swift
  Inception/Inception/Network/Manager/SleepTrackDataManager.swift
  Inception/Inception/Network/Models/Inception.xcdatamodeld/.xccurrentversion
  Inception/Inception/Network/Models/Inception.xcdatamodeld/Inception.xcdatamodel/contents
  Inception/Inception/Screens/Base.lproj/LaunchScreen.storyboard
  Inception/Inception/ViewController.swift
Labels: ⚙️ setting, 😎 알로라

#52 ✅ add : Core Data에 SleepRecord 저장
  Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
Labels: ✨ feat, 😎 닉, 📄 AlarmCalculatorView

#55 ✨ feat : 추천 알람 추가 시 알람 리스트와 연결되도록 구현
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AlarmTime.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
  Inception/Inception/Screens/AlarmClock/Scheduler.swift
Labels: ✨ feat, 😎 밀리, 😎 태니, 📄 AlarmCalculatorView

#56 ✨ feat : 수면만족도 CoreData 기록 #42 Open 3 tasks
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
  Inception/Inception/Screens/SleepSatisfaction/SleepSatisfacationViewController.swift
Labels: ✨ feat, 😎 에이버리, 📄 SleepSatisfactionView

#57 ✅ add : 저장된 알람 목록 선택 시 alert 생성 및 현재 알람으로 변경 #13
  Inception/Inception/Global/CoreData/AlarmDataManager.swift
  Inception/Inception/Screens/AlarmList/AlarmListViewController.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
Labels: 🐛 fix, ✨ feat

#58 ✅ add : 앱 아이콘 추가 및 Launch Screen UI 구성 + UI 디테일 수정
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Inception/Inception.xcodeproj/xcshareddata/xcschemes/Inception.xcscheme
  Inception/Inception/AppDelegate.swift
  Inception/Inception/Base.lproj/LaunchScreen.storyboard
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Inception/Inception/Global/Resource/Assets.xcassets/AppIcon.appiconset/appstore.png
  Inception/Inception/Global/Resource/Assets.xcassets/launchscreen.imageset/Contents.json
  Inception/Inception/Global/Resource/Assets.xcassets/launchscreen.imageset/launchscreen.png
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.storyboard
  Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmList/AlarmListViewController.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
  Inception/Inception/Screens/TabBar/TabBarController.swift
Labels: ⚙️ setting, 😎 알로라, 📄 AlarmCalculatorView, 📄 AlarmListView, 📄 SleepTrackerView, 📄 SleepSatisfactionView, 💄 design

#64 ✅ add : 노티 알림 타이틀 수정 및 기상 기반 알람 정렬 수정
  Inception/Inception.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
  Inception/Inception/Screens/AlarmClock/Scheduler.swift
Labels: 😎 알로라, 📄 AlarmCalculatorView, 💄 design

#62 🐛fix : 알람 해제가 안되는 버그, 취침 알람이 안 오는 버그 해결
  Inception/Inception/AppDelegate.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmList/AlarmListViewController.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
Labels: 🐞 bug, 😎 닉

#66 🚚 move : 파일 및 폴더 이동
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/Resource/Sounds/alarmSound.m4a
  Inception/Inception/Global/Supports/AppDelegate.swift
  Inception/Inception/Global/Supports/Info.plist
  Inception/Inception/Global/Supports/SceneDelegate.swift
  Inception/Inception/Network/Manager/AlarmDataManager.swift
  Inception/Inception/Network/Manager/SleepTrackDataManager.swift
  Inception/Inception/Network/Models/Inception.xcdatamodeld/.xccurrentversion
  Inception/Inception/Network/Models/Inception.xcdatamodeld/Inception.xcdatamodel/contents
  Inception/Inception/Screens/Base.lproj/LaunchScreen.storyboard
  Inception/Inception/Screens/Base.lproj/Main.storyboard
  Inception/Inception/Screens/ViewController.swift
Labels: ⚙️ setting, 😎 알로라

#70 🐞 bug : 특정경우 알람등록시 new 탭바뱃지가 확인해도 삭제안되는 문제
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
Labels: 🐛 fix, 🐞 bug, 😎 에이버리

#74 🐛 fix : 알람시계 원 중앙에서 벗어나는 버그 해결
  Inception/Inception/Screens/AlarmClock/AlarmClockView.storyboard
Labels: 🐞 bug, 😎 닉, 📄 AlarmClockView

#76 🐛 Hotfix/ 알람시계 뷰에서 알람이 울리지 않는 버그 해결
  Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
  Inception/Inception/Screens/AlarmClock/Scheduler.swift
Labels: 🐛 fix, ✨ feat, 😎 닉, 📄 AlarmClockView

#81 🐛 fix : '알람 찾기' 버튼 클릭 Animation 없던 문제 해결
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.storyboard
Labels: 🐛 fix, 😎 태니, 📄 AlarmCalculatorView, 💄 design

#79 ✅ add : 새로운 알람 설정 시, 무음이나 방해금지 주의 UX Writing 추가
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
Labels: 😎 태니, 📄 AlarmCalculatorView, 📄 AlarmListView, 💄 design

#78 ✅ add : 저장된 알람 중복 체크 및 처리
  Inception/Inception/Network/Manager/AlarmDataManager.swift
  Inception/Inception/Network/Models/AlarmItem+CoreDataProperties.swift
  Inception/Inception/Network/Models/Inception.xcdatamodeld/Inception.xcdatamodel/contents
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.swift
Labels: 🐛 fix, 😎 밀리, 📄 AlarmCalculatorView, 📄 AlarmListView

#82 ✨ feat : 온보딩 구현
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/Extension/App/UserDefaults+.swift
  Inception/Inception/Global/Extension/View/UIButton+.swift
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-1.imageset/Contents.json
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-1.imageset/onboarding-1.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-1.imageset/onboarding-1@2x.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-1.imageset/onboarding-1@3x.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-2.imageset/Contents.json
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-2.imageset/onboarding-2.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-2.imageset/onboarding-2@2x.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-2.imageset/onboarding-2@3x.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-3.imageset/Contents.json
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-3.imageset/onboarding-3.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-3.imageset/onboarding-3@2x.png
  Inception/Inception/Global/Resource/Assets.xcassets/onboarding-3.imageset/onboarding-3@3x.png
  Inception/Inception/Global/Supports/SceneDelegate.swift
  Inception/Inception/Screens/OnBoarding/OnBoardingPageViewController.swift
  Inception/Inception/Screens/OnBoarding/OnBoardingViewController.swift
Labels: ✨ feat, 😎 에이버리

#84 🐛 fix : 알람 찾기에서 알람이 추가가 안되는 현상
  Inception/Inception/Screens/OnBoarding/OnBoardingPageViewController.swift
Labels: 🐛 fix, 🐞 bug, 😎 에이버리
