Repository DeveloperAcademy-POSTECH/MC3-Team13-Inception, pull requests merged in 2022-07, with the labels that each got.

#5 ⚙️ setting : Auto-Assigner 설정
  .github/auto_assign.yml
Labels: ⚙️ setting, 😎 알로라

#14 ✨ feat : 수면만족도화면 UI 구성
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/Extension/View/UIButton+.swift
  Inception/Inception/Global/Extension/View/UIStackView+.swift
  Inception/Inception/Global/Extension/View/UIView+.swift
  Inception/Inception/SceneDelegate.swift
  Inception/Inception/Screens/SleepSatisfaction/SleepSatisfacation.storyboard
  Inception/Inception/Screens/SleepSatisfaction/SleepSatisfacationViewController.swift
  Inception/Inception/Screens/SleepSatisfaction/Views/EmojiButton.swift
Labels: ✨ feat, 😎 에이버리, 📄 SleepSatisfactionView, 💄 design

#25 ✅ add : assign-bot에 멘토님도 추가
  .github/auto_assign.yml
Labels: ⚙️ setting

#16 ✅ add : 수면기록화면 UI 구성
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Screens/SleepTracker/DailySleepTrack.swift
  Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
  Inception/Inception/Screens/SleepTracker/SleepTrackerStoryboard.storyboard
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
Labels: 😎 밀리, 📄 SleepTrackerView, 💄 design

#18 ✅ add : 알람 목록 셀 UI 구성
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
  Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.xib
Labels: 😎 에이버리, 📄 AlarmListView, 💄 design

#26 ✨ feat : Alarm, SleepRecord Model 생성
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/Extension/Date/Date+.swift
  Inception/Inception/Network/Models/Alarm.swift
  Inception/Inception/Network/Models/SleepRecord.swift
  Inception/Inception/Screens/SleepSatisfaction/SleepSatisfacationViewController.swift
Labels: ✨ feat, 😎 에이버리

#28 🐛 fix : Alarm 및 SleepRecord Model 초기화 코드 추가
  Inception/Inception/Network/Models/Alarm.swift
  Inception/Inception/Network/Models/SleepRecord.swift
Labels: 🐛 fix, 😎 에이버리

#15 ✨ feat : 기상알람 UI 구성 및 시계 구현
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Screens/AlarmClock/AlarmClockView.storyboard
  Inception/Inception/Screens/AlarmClock/AlarmClockViewController.swift
Labels: ✨ feat, 😎 닉, 📄 AlarmClockView

#17 ✅ add : 알람추천화면 상단 UI 구성
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculator.storyboard
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
Labels: 😎 너울, 📄 AlarmCalculatorView, 💄 design

#19 ✅ add : 알람 추천 목록 Cell Layout 구현
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculator.storyboard
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
  Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AlarmTime.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.xib
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.xib
  Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
Labels: 😎 태니, 📄 AlarmCalculatorView, 💄 design

#30 ✅ add : 알람 목록 뷰 UI Layout 구성
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Network/Models/Alarm.swift
  Inception/Inception/Screens/AlarmList/AlarmList.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
  Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
  Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.xib
Labels: 😎 알로라, 📄 AlarmListView, 💄 design

#31 ✨ feat : Core Data 연동, 데이터 저장 및 불러오기 #21
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/CoreData/AlarmDataManager.swift
  Inception/Inception/Global/CoreData/Inception.xcdatamodeld/.xccurrentversion
  Inception/Inception/Global/CoreData/Inception.xcdatamodeld/Inception.xcdatamodel/contents
  Inception/Inception/Global/CoreData/SleepRecordItem+CoreDataProperties.swift
  Inception/Inception/Global/CoreData/SleepTrackDataManager.swift
  Inception/Inception/Global/Extension/Date/Date+.swift
  Inception/Inception/Inception.xcdatamodeld/Inception.xcdatamodel/contents
  Inception/Inception/Network/Models/AlarmItem+CoreDataClass.swift
  Inception/Inception/Network/Models/AlarmItem+CoreDataProperties.swift
  Inception/Inception/Network/Models/SleepRecord.swift
  Inception/Inception/Network/Models/SleepRecordItem+CoreDataClass.swift
  Inception/Inception/Network/Models/SleepRecordItem+CoreDataProperties.swift
  Inception/Inception/Screens/SleepTracker/DailySleepTrackerTableViewCell.swift
  Inception/Inception/Screens/SleepTracker/SleepTrackerStoryboard.storyboard
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
Labels: ✨ feat, 😎 밀리, 📄 SleepTrackerView

#37 🐛 fix : 빌드 안되는 문제 해결
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/CoreData/Inception.xcdatamodeld/Inception.xcdatamodel/contents
  Inception/Inception/Global/CoreData/SleepRecordItem+CoreDataProperties.swift
  Inception/Inception/Global/CoreData/SleepTrackDataManager.swift
  Inception/Inception/Network/Models/AlarmItem+CoreDataProperties.swift
  Inception/Inception/Network/Models/SleepRecordItem+CoreDataProperties.swift
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
Labels: 🐛 fix

#36 ✨ feat : 탭바 추가 및 화면연결
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/Protocol/Storyboarded.swift
  Inception/Inception/SceneDelegate.swift
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.storyboard
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.swift
  Inception/Inception/Screens/AlarmClock/AlarmClockViewController.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
  Inception/Inception/Screens/SleepSatisfaction/SleepSatisfacationViewController.storyboard
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.storyboard
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.swift
  Inception/Inception/Screens/TabBar/TabBarController.swift
Labels: ✨ feat, 😎 에이버리

#39 ✨ feat : 테이블 편집 기능 및 empty view 구현
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/Extension/View/UIImage+.swift
  Inception/Inception/Network/Models/Alarm.swift
  Inception/Inception/Screens/AlarmList/AlarmListViewController.storyboard
  Inception/Inception/Screens/AlarmList/AlarmListViewController.swift
  Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.swift
  Inception/Inception/Screens/AlarmList/Cell/AlarmListCell.xib
Labels: ✨ feat, 😎 알로라, 📄 AlarmListView, 💄 design

#41 ✨ feat : 알람 추천 목록에서 시간 설정 후 추천 알람 표시 기능 구현 #20
  Inception/Inception.xcodeproj/project.pbxproj
  Inception/Inception/Global/Extension/App/UIApplication+.swift
  Inception/Inception/Screens/AlarmCalculator/AlarmCalculatorViewController.storyboard
  Inception/Inception/Screens/AlarmCalculator/AwakeBasedViewController.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecoCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/AwakeBasedRecommendCell.xib
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecoCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.swift
  Inception/Inception/Screens/AlarmCalculator/Cell/SleepBasedRecommendCell.xib
  Inception/Inception/Screens/AlarmCalculator/SleepBasedViewController.swift
  Inception/Inception/Screens/SleepTracker/SleepTrackerTableViewController.storyboard
Labels: ✨ feat, 😎 태니, 📄 AlarmCalculatorView, 💄 design
